# Usage example:
#   ```SWARM_MANAGER_HOSTNAME=sprocket ENDPOINT_HOSTNAME=tada.cnx.org docker -H sprocket stack deploy -c docker-stack.testing.yml testing```
# Where the swarm manager is on the host named 'sprocket'.
# The endpoint is 'tada.cnx.org' in this example, in production for example, it would be 'cnx.org'.

version: '3'
services:
  ###
  # third-party or out-of-scope services
  ###
  proxy-openstax-org:
    image: openstax/proxy-openstax-org:testing-stack
    ports:
      - "8900:80"
    #: This is essentially an nginx container with custom configuration
    # image: nginx:latest
    # volumes:
    #   - .dockerfiles/proxy-openstax-org.conf:/etc/nginx/conf.d/default.conf:ro
    #: Image build instructions:
    # $ docker run --name img -d nginx:latest
    # $ cat .dockerfiles/proxy-openstax-org.conf | docker exec -i img /bin/bash -c "cat /etc/nginx/conf.d/default.conf"
    # $ docker commit -m "..." <container-id> openstax/proxy-openstax-org:testing-stack
    # $ docker push openstax/proxy-openstax-org:testing-stack

  ###
  # core third-party components
  ###
  db:
    image: openstax/cnx-db:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - DB_URL=postgresql://rhaptos@/repository
      - DB_SUPER_URL=postgresql://rhaptos_admin@/repository

  memcached:
    image: memcached:latest

  # FIXME: We should use a single rabbitmq instance, but this is easier to configure
  broker-publishing:
    image: rabbitmq:3
  #  environment:
  #    - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
  #    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
  broker-press:
    image: rabbitmq:3
  #  environment:
  #    - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
  #    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  ###
  # CNX components
  ###

  archive:
    image: openstax/cnx-archive:latest
    # command: <use default entry-point>
    ports:
      - "8800:6543"
    depends_on:
      - db
      - memcached

  publishing:
    image: openstax/cnx-publishing:dev
    command: bash -c "pserve $${PYRAMID_INI}"
    ports:
      - "9000:6543"
    environment:
      - DB_URL
      - DB_SUPER_URL
      - AMQP_URL=${BASE_PUBLISHING_AMQP_URL}
      - USERS=smoo,pauperized1821(horrendously
      - MODERATORS=smoo
      - ADMINISTRATORS=smoo
      - MATHMLCLOUD_URL
      - MEMCACHE_HOST
      - EXERCISES_URL

  publishing-worker:
    image: openstax/cnx-publishing:dev
    command: bash -c "celery worker -A cnxpublishing -Q default,deferred --loglevel debug"
    environment:
      - DB_URL
      - DB_SUPER_URL
      - AMQP_URL=${BASE_PUBLISHING_AMQP_URL}
      - USERS=smoo,pauperized1821(horrendously
      - MODERATORS=smoo
      - ADMINISTRATORS=smoo
      - MATHMLCLOUD_URL
      - MEMCACHE_HOST
      - EXERCISES_URL

  channel-processing:
    image: openstax/cnx-publishing:dev
    command: bash -c "cnx-publishing-channel-processing $${PYRAMID_INI}"
    environment:
      - DB_URL
      - DB_SUPER_URL
      - AMQP_URL=${BASE_PUBLISHING_AMQP_URL}
      - USERS=smoo,pauperized1821(horrendously
      - MODERATORS=smoo
      - ADMINISTRATORS=smoo
      - MATHMLCLOUD_URL
      - MEMCACHE_HOST
      - EXERCISES_URL

  press:
    image: openstax/cnx-press:dev
    command: gunicorn -b 0.0.0.0:6543 --access-logfile - --error-logfile - -n press --timeout=180 wsgi:app
    environment:
      # TODO: shared dir volume
      - SHARED_DIR=/app/var
      - DB_URL
      - DB_SUPER_URL
      - AMQP_URL=${BASE_PRESS_AMQP_URL}

  press-worker:
    image: openstax/cnx-press:dev
    command: celery -A press worker --beat --loglevel debug
    environment:
      # TODO: shared dir volume
      - SHARED_DIR=/app/var
      - DB_URL
      - DB_SUPER_URL
      - AMQP_URL=${BASE_PRESS_AMQP_URL}

  ui:
    image: openstax/cnx-webview:dev
    ports:
      - "8600:80"
    environment:
      - ENVIRONMENT=prod
      - ARCHIVE_HOST=archive-${ENDPOINT_HOSTNAME}
      - ARCHIVE_PORT=80
      # FIXME: Can't remove this until we've got SSL over *${ENDPOINT_HOSTNAME}
      - OPENSTAX_HOST=${SWARM_MANAGER_HOSTNAME}
      - OPENSTAX_PORT=8900

  http-cache:
    image: openstax/cnx-varnish:latest
    command: "-T 127.0.0.1:6082"
    ports:
      - "80:80"
    environment:
      - VARNISH_WEBVIEW_HOST=ui
      - VARNISH_WEBVIEW_PORT=80
      - VARNISH_ARCHIVE_HOST=archive
      - VARNISH_ARCHIVE_PORT=6543
      - VARNISH_PUBLISHING_HOST=publishing
      - VARNISH_PUBLISHING_PORT=6543
      - VARNISH_PRESS_HOST=press
      - VARNISH_PRESS_PORT=6543
      - VARNISH_ARCLISHING_DOMAIN=archive-${ENDPOINT_HOSTNAME}
      - VARNISH_FRONTEND_DOMAIN=${ENDPOINT_HOSTNAME}

volumes:
  pgdata:
